# Copyright (C) 2019 Ola Benderius
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: '2'

services:
    dev-camera-rtp0:
        container_name: dev-camera-rtp0
        image: chalmersrevere/opendlv-device-camera-rtp-amd64:v0.0.2
        ipc: "host"
        restart: "always"
        network_mode: "host"
        command: "opendlv-device-camera-rtp --url=rtsp://192.168.1.213:554/axis-media/media.amp?camera=1 --cid=100 --id=0 --client-port-a=35000"
    
    dev-camera-rtp1:
        container_name: dev-camera-rtp1
        image: chalmersrevere/opendlv-device-camera-rtp-amd64:v0.0.2
        ipc: "host"
        restart: "always"
        network_mode: "host"
        command: "opendlv-device-camera-rtp --url=rtsp://192.168.1.213:554/axis-media/media.amp?camera=2 --cid=100 --id=1 --client-port-a=35002"
    
    dev-camera-rtp2:
        container_name: dev-camera-rtp2
        image: chalmersrevere/opendlv-device-camera-rtp-amd64:v0.0.2
        ipc: "host"
        restart: "always"
        network_mode: "host"
        command: "opendlv-device-camera-rtp --url=rtsp://192.168.1.213:554/axis-media/media.amp?camera=3 --cid=100 --id=2 --client-port-a=35004"
    
    dev-camera-rtp3:
        container_name: dev-camera-rtp3
        image: chalmersrevere/opendlv-device-camera-rtp-amd64:v0.0.2
        ipc: "host"
        restart: "always"
        network_mode: "host"
        command: "opendlv-device-camera-rtp --url=rtsp://192.168.1.213:554/axis-media/media.amp?camera=4 --cid=100 --id=3 --client-port-a=35006"

    vehicle-view:
        container_name: opendlv-vehicle-view
        image: chalmersrevere/opendlv-vehicle-view-multi:v0.0.60
        restart: always
        network_mode: "host"
        volumes:
        - ~/recordings:/opt/vehicle-view/recordings
        - /var/run/docker.sock:/var/run/docker.sock
        environment:
        - OD4SESSION_CID=100
        - PLAYBACK_OD4SESSION_CID=200
        - OPENDLV_VEHICLE_VIEW_PLATFORM=Rhino
        ports:
        - "8081:8081"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -15 node index.js"

    dev-gps-nmea:
        container_name: dev-gps-nmea
        image: nmea-udp:latest
        restart: on-failure
        network_mode: "host"
        command: "--nmea_ip=0.0.0.0 --nmea_port=8500 --cid=100"

    device-motor-bellmarineac34-0:
        container_name: opendlv-device-motor-bellmarineac34-0
        image: chalmersrevere/opendlv-device-motor-bellmarineac34-amd64:v0.0.2
        network_mode: "host"
        command: "opendlv-device-motor-bellmarineac34 --cid=100 --can=can0 --sender-stamp-offset=0"
    
    device-motor-bellmarineac34-1:
        container_name: opendlv-device-motor-bellmarineac34-1
        image: chalmersrevere/opendlv-device-motor-bellmarineac34-amd64:v0.0.2
        network_mode: "host"
        command: "opendlv-device-motor-bellmarineac34 --cid=100 --can=can1 --sender-stamp-offset=10 --flip"

    device-gps-nmea:
        container_name: opendlv-device-gps-nmea
        image: chalmersrevere/opendlv-device-gps-nmea-multi:v0.0.13
        network_mode: "host"
        command: "opendlv-device-gps-nmea --nmea_ip=192.168.1.5 --nmea_port=8500 --cid=100"

    ui-seacat:
        container_name: opendlv-ui-seacat
        image: chalmersrevere/opendlv-ui-seacat-amd64:v0.0.2
        network_mode: "host"
        command: "opendlv-ui-seacat --cid=100 --http-root=/srv/http --port=8000"

